# Generated by Django 5.2.1 on 2025-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('plot', models.TextField(blank=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, verbose_name='IMDb ID')),
                ('genres', models.ManyToManyField(related_name='movies', to='mi_api.genredb')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'Movie',
            },
        ),
    ]
